name: build

on:
  push:
    branches:
      - 'master'
    tags:
      - 'v*'
  pull_request:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v4
        with:
          go-version: 1.22
          cache: true
      - run: go mod tidy
      - run: sudo apt-get install gcc libgtk-3-dev libayatana-appindicator3-dev 
      - run: go test -v ./...
      -
        name: Run goreleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
